// <auto-generated />
using System;
using AbonnementsAPi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AbonnementsAPi.Migrations
{
    [DbContext(typeof(AbonnementsAPIContext))]
    [Migration("20190626132758_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("AbonnementsAPi.Models.Abonnements", b =>
                {
                    b.Property<int>("aboId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("aboDateDebut");

                    b.Property<DateTime>("aboDateFin");

                    b.Property<int>("aboFKCli");

                    b.Property<int>("aboFKMag");

                    b.Property<int>("aboStatus");

                    b.HasKey("aboId");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Clients", b =>
                {
                    b.Property<int>("cliId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("cliAuthKey");

                    b.Property<string>("cliCCV");

                    b.Property<DateTime?>("cliDateNaissance");

                    b.Property<string>("cliExpiCarte");

                    b.Property<string>("cliLieuNaissance");

                    b.Property<string>("cliMail");

                    b.Property<string>("cliNom");

                    b.Property<string>("cliNumCart");

                    b.Property<string>("cliPassword");

                    b.Property<string>("cliPhone");

                    b.Property<string>("cliPrenom");

                    b.HasKey("cliId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Employer", b =>
                {
                    b.Property<int>("empId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("empAuthKey");

                    b.Property<string>("empLogin");

                    b.Property<string>("empPassword");

                    b.HasKey("empId");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Historique", b =>
                {
                    b.Property<int>("hisId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("hisDate");

                    b.Property<int>("hisFKCli");

                    b.Property<int>("hisFKEmp");

                    b.Property<string>("hisMotif")
                        .IsRequired();

                    b.Property<string>("hisMoyen")
                        .IsRequired();

                    b.HasKey("hisId");

                    b.ToTable("Historique");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Log", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("logDate");

                    b.Property<string>("logDescription")
                        .IsRequired();

                    b.HasKey("logId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Magazines", b =>
                {
                    b.Property<int>("magId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("magDescription")
                        .IsRequired();

                    b.Property<int>("magNbVolumeAnnee");

                    b.Property<string>("magPhotoCouverture");

                    b.Property<decimal>("magPrixAnnuel");

                    b.Property<string>("magTitre")
                        .IsRequired();

                    b.HasKey("magId");

                    b.ToTable("Magazines");
                });

            modelBuilder.Entity("AbonnementsAPi.Models.Paiement", b =>
                {
                    b.Property<int>("uuid")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("amount");

                    b.Property<int>("cardMonth");

                    b.Property<string>("cardNumber");

                    b.Property<int>("cardYear");

                    b.Property<string>("cid");

                    b.Property<string>("transaction");

                    b.HasKey("uuid");

                    b.ToTable("Paiement");
                });
#pragma warning restore 612, 618
        }
    }
}
